name: CI

on: ["push", "pull_request"]

jobs:
  ci:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.12.3'
        otp-version: '24.1'

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.mix
          deps
          _build
        key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}

    - name: Install dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix deps.compile
        mix dialyzer --plt

    - name: Compile
      run: mix compile --warnings-as-errors

    - name: Lint format
      run: mix format --check-formatted

    - name: Lint dialyzer
      run: mix dialyzer --no-check

    - name: Run tests
      run: mix coveralls.github
      env:
        MIX_ENV: test
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
